export const SET_LOGIN_USER_DATA = 'SET_LOGIN_USER_DATA';
export const SET_REGISTER_USER_DATA = 'SET_REGISTER_USER_DATA';

export const SET_VEHICLE_DATA = 'SET_VEHICLE_DATA';
export const SET_NEW_VEHICLE_DATA = 'SET_NEW_VEHICLE_DATA';

export const SET_DRIVERS_DATA = 'SET_DRIVERS_DATA';
export const SET_CURRENT_SHIFT_DATA = 'SET_CURRENT_SHIFT_DATA';


export const SET_INCREMENT_TIMER = 'SET_INCREMENT_TIMER';

export const SET_USER_PROFILE_DATA = 'SET_USER_PROFILE_DATA';
export const LOGOUT_USER = 'LOGOUT_USER';


export const SET_SUBSCRIPTION_USER_DATA = 'SET_SUBSCRIPTION_USER_DATA';