export const SET_LOGIN_USER_DATA = 'SET_LOGIN_USER_DATA';
export const SET_REGISTER_USER_DATA = 'SET_REGISTER_USER_DATA';

export const SET_USER_PROFILE_DATA = 'SET_USER_PROFILE_DATA';
export const LOGOUT_USER = 'LOGOUT_USER';